# Site settings
title: HT Blog
SEOTitle: 浩天的博客 | HT Blog
header-img: img/wKgBs1g4HeKAfY6IAAxVQt_lR7E07.jpeg
email: 1479794847@qq.com
#description: "hahahahahahhaha."
description: "欢迎来到浩天的博客O(∩_∩)O"
keyword: "HT, HT Blog, 方浩天的博客, fanghaotian, 方浩天, curry,nba， Apple, iPhone"
url: "https://fanghaotianHT.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/fanghaotianHT/fanghaotianHT.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "God doesn't play dice with the universe."
sidebar-avatar: /img/haha.png     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     3561547802
zhihu_username:     tian-tian-up-46
github_username:    fanghaotianHT
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
twitter_username:   likecurryhaha




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
#disqus_username: fanghaotianHT
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 590d4ba9ef79b05790af                            #生成的clientID
  clientSecret: 28b375625b229ce96e8ec6f0ff71648f763c5121    #生成的clientSecret
  repo: fanghaotianHT.github.io    #仓库名称
  owner: fanghaotianHT    #github用户名
  admin: fanghaotianHT
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 1880568bcada311a9668615ba136aebe

# Google Analytics
ga_track_id: 'UA-110085522-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        #title: "WY",
        #href: "http://zhengwuyang.com"
    },{
        title: "知乎·HT",
        href: "https://www.zhihu.com/people/tian-tian-up-46/activities"
    }
]
